---
- name: Setup a new DigitalOcean droplet
  # Requires a target to be set. If no target is defined, nothing is
  hosts: "{{ target | default('no_host') }}"
  
  # Source: https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-20-04
  tasks:

  - name: Remove user, if it exists
    ansible.builtin.user:
      name: "{{ user }}"
      state: absent
      remove: yes

  - name: Ensure group "{{ user }}" exists
    ansible.builtin.group:
      name: "{{ user }}"
      state: present

  - name: Create new user
    ansible.builtin.user:
      name: "{{ user }}"
      password: "{{ password | password_hash('sha512') }}"
      groups: sudo,marvin

  # Use DigitalOcean's firewall feature to further control access
  # (ie specific IP address source, DO tag, etc)
  - name: Enable UFW
    community.general.ufw:
      state: enabled
  
  - name: Allow SSH access
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Allow SSH access to new user
    command: "rsync --archive --chown={{ user }}:{{ user }} ~/.ssh /home/{{ user }}"
