networks:
    monolith:
        name: monolith

volumes:
    portainer_data:

services:
    portainer:
        image: portainer/portainer-ce:2.13.1-alpine
        container_name: portainer
        networks:
            - monolith
        expose:
            - "9443"
        ports:
            - "8000:8000"
        restart: always
        volumes:
            - portainer_data:/data
            - /var/run/docker.sock:/var/run/docker.sock
