networks:
    default:
        external:
            name: monolith

volumes:
    database_backup:
    database_data:

services:
    tunnel:
        image: cloudflare/cloudflared:2022.5.1
        container_name: tunnel
        command: tunnel --no-autoupdate run --token $TUNNEL_TOKEN
        restart: always

    server-gateway:
        image: ghcr.io/marvinisaac/devops-playground/server-gateway:v0.1.17
        container_name: server-gateway
        expose:
            - "8080"
        restart: always

    database:
        image: ghcr.io/marvinisaac/devops-playground/database:v0.1.18
        container_name: database
        environment:
            MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - database_data:/var/lib/mysql
            - database_backup:/backup

    scheduler:
        image: ghcr.io/marvinisaac/devops-playground/scheduler:v0.1.20
        container_name: scheduler
        environment:
            MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
            SLACK_WEBHOOK: $SLACK_WEBHOOK
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
