networks:
    default:
        external:
            name: monolith

services:
    tunnel:
        image: cloudflare/cloudflared:2022.5.1
        container_name: tunnel
        command: tunnel --no-autoupdate run --token $TUNNEL_TOKEN
        restart: always

    server-gateway:
        image: ghcr.io/marvinisaac/devops-playground/server-gateway:v0.1.17
        container_name: server-gateway
        expose:
            - "8080"
        restart: always
