networks:
    default:
        external:
            name: monolith

volumes:
    database_data:

services:
    tunnel:
        image: cloudflare/cloudflared:2022.5.1
        container_name: tunnel
        command: tunnel --no-autoupdate run --token $TUNNEL_TOKEN
        restart: always

    server-gateway:
        image: ghcr.io/marvinisaac/devops-playground/server-gateway:v0.1.17
        container_name: server-gateway
        expose:
            - "8080"
        restart: always

    database:
        image: ghcr.io/marvinisaac/devops-playground/database:v0.1.18
        container_name: database
        environment:
            MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - database_data/data:/var/lib/mysql
            - database_data/backup:/backup
