networks:
    default:
        external:
            name: monolith

volumes:
    database_backup:
    database_data:
    nocodb:

services:
    tunnel:
        image: cloudflare/cloudflared:2022.5.1
        container_name: tunnel
        command: tunnel --no-autoupdate run --token $TUNNEL_TOKEN
        restart: always

    server-gateway:
        image: ghcr.io/marvinisaac/devops-playground/server-gateway:0.2.0
        container_name: server-gateway
        expose:
            - "8080"
        restart: always

    database:
        image: ghcr.io/marvinisaac/devops-playground/database:0.2.0
        container_name: database
        environment:
            MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - database_data:/var/lib/mysql
            - database_backup:/backup

    scheduler:
        image: ghcr.io/marvinisaac/devops-playground/scheduler:0.2.1
        container_name: scheduler
        environment:
            MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
            SLACK_WEBHOOK: $SLACK_WEBHOOK
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

    nocodb:
        image: nocodb/nocodb:0.90.11
        container_name: nocodb
        expose:
            - "8080"
        restart: always
        volumes:
            - nocodb:/usr/app/data
        environment:
            NC_DB: $NOCODB

    shlink:
        image: shlinkio/shlink:stable
        container_name: shlink
        environment:
            DEFAULT_DOMAIN: $SHLINK_DEFAULT_DOMAIN
            IS_HTTPS_ENABLED: "false"
            GEOLITE_LICENSE_KEY: $SHLINK_GEOLITE_LICENSE_KEY
            DB_DRIVER: "mysql"
            DB_HOST: $SHLINK_DB_HOST
            DB_NAME: $SHLINK_DB_NAME
            DB_PASSWORD: $SHLINK_DB_PASSWORD
            DB_USER: $SHLINK_DB_USER
        expose:
            - "8080"
        restart: always
