#!/bin/sh

case $1 in
    "scheduler")
        VERSION_FILE="_project/monolith/image/scheduler/VERSION"
        ;;
    "server-gateway")
        VERSION_FILE="_project/monolith/image/server-gateway/VERSION"
        ;;
    *)
        VERSION_FILE="VERSION"
        ;;
esac

case $2 in
    "")
        VERSION_TYPE="patch"
        ;;
    *)
        VERSION_TYPE=$2
        ;;
esac

./_script/semver.sh bump $VERSION_TYPE `cat $VERSION_FILE` > $VERSION_FILE
