---
- name: Extend disk to 100%
  # Requires a target to be set. If no target is defined, nothing is
  hosts: "{{ target | default('no_host') }}"
  become: yes

  tasks:
    # Run `sudo cfdisk` manually

    - name: Extend physical volume to 100%
      community.general.lvg:
        vg: ubuntu-vg
        pvs: /dev/sda3
        pvresize: yes

    - name: Extend logical volume to 100%
      community.general.lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: 100%PVS
        resizefs: true
