---
- name: Allow MySQL access
  # Requires a target to be set. If no target is defined, nothing is
  hosts: "{{ target | default('no_host') }}"
  become: yes
  tasks:
    - name: Allow MySQL access
      community.general.ufw:
        rule: allow
        port: '3306'
